# Unordered list style
MD004:
  style: dash

# Line length
MD013:
  tables: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Inline HTML
MD033:
  allowed_elements: ['p', 'img', 'picture', 'source']

# Code block style
MD046:
  style: fenced
