name: Neon Create Branch GitHub Action
description:
  Creates a new branch in a Neon project, if the branch already exists it will
  return the existing branch.
author: Neon Database
branding:
  icon: align-left
  color: green
inputs:
  api_key:
    description: The Neon API key
    required: true
  api_host:
    description: The Neon API Host
    default: https://console.neon.tech/api/v2
  branch_name:
    description: The name of the branch to create
  project_id:
    description: The Neon project ID
    required: true
  parent_branch:
    description: The parent branch to create the new branch from
  prisma:
    description: Whether to use prisma or not
    default: 'false'
  database:
    description: The database name
    default: 'neondb'
  role:
    description: The role of the user
    default: 'neondb_owner'
  branch_type:
    description: The type of branch to create, 'default' or 'schema-only'
    default: 'default'
  ssl:
    description:
      "The SSL mode for the connection string. Supported values are: 'require',
      'verify-ca', 'verify-full', 'omit'."
    default: 'require'
  suspend_timeout:
    description:
      Duration of inactivity in seconds after the compute endpoint is suspended
    default: '0'
outputs:
  db_url:
    description: The database connection string
  db_url_pooled:
    description: The database connection string with connection pooling
  db_host:
    description: The database host
  db_host_pooled:
    description: The database host with connection pooling
  password:
    description: The database password
  branch_id:
    description: The ID of the branch
  created:
    description: Whether the branch was created or reused

runs:
  using: node20
  main: dist/index.js
